---
version: 1
labels:
  - label: 'small'
    size-below: 10
  - label: 'medium'
    size-above: 9
    size-below: 100
  - label: 'large'
    size-above: 100
  - label: 'documentation'
    files:
      - '.+.md'
      - 'LICENSE'
  - label: 'config'
    files:
      - '.github'
      - '.*'
  - label: 'tests'
    files:
      - 'test'
  - label: 'dependencies'
    files:
      - 'package*.json'
  - label: 'code'
    files:
      - 'lib'

